// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package db

import (
	"context"
	"time"
)

const createComment = `-- name: CreateComment :one
WITH inserted AS (
  INSERT INTO comments (
    issue_id,
    text
  )
  SELECT
    $1,
    $2
  WHERE EXISTS (
    SELECT 1
    FROM issues
    WHERE id = $1
  )
  RETURNING
    id,
    issue_id,
    text,
    created_at,
    updated_at
)
SELECT
  i.id,
  i.text,
  i.created_at,
  i.updated_at,
  p.id          AS issue_id,
  p.title        AS issue_title
FROM inserted i
JOIN issues p ON p.id = i.issue_id
`

type CreateCommentParams struct {
	IssueID int64
	Text    string
}

type CreateCommentRow struct {
	ID         int64
	Text       string
	CreatedAt  time.Time
	UpdatedAt  time.Time
	IssueID    int64
	IssueTitle string
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (CreateCommentRow, error) {
	row := q.db.QueryRow(ctx, createComment, arg.IssueID, arg.Text)
	var i CreateCommentRow
	err := row.Scan(
		&i.ID,
		&i.Text,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IssueID,
		&i.IssueTitle,
	)
	return i, err
}
