// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: issues.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIssue = `-- name: CreateIssue :one
WITH inserted AS (
    INSERT INTO issues (
      project_id,
      title,
      description,
      status,
      priority,
      due_date
    )
    SELECT
      $1,
      $2,
      $3,
      $4,
      $5,
      $6
    WHERE EXISTS (
      SELECT 1
      FROM projects
      WHERE id = $1
    )
    RETURNING
      id,
      project_id,
      title,
      description,
      status,
      priority,
      due_date,
      created_at,
      updated_at
)
SELECT
  i.id,
  i.title,
  i.description,
  i.status,
  i.priority,
  i.due_date,
  i.created_at,
  i.updated_at,
  p.id          AS project_id,
  p.name        AS project_name
FROM inserted i
JOIN projects p ON p.id = i.project_id
`

type CreateIssueParams struct {
	ProjectID   int64
	Title       string
	Description string
	Status      string
	Priority    string
	DueDate     pgtype.Date
}

type CreateIssueRow struct {
	ID          int64
	Title       string
	Description string
	Status      string
	Priority    string
	DueDate     pgtype.Date
	CreatedAt   time.Time
	UpdatedAt   time.Time
	ProjectID   int64
	ProjectName string
}

func (q *Queries) CreateIssue(ctx context.Context, arg CreateIssueParams) (CreateIssueRow, error) {
	row := q.db.QueryRow(ctx, createIssue,
		arg.ProjectID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.DueDate,
	)
	var i CreateIssueRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectID,
		&i.ProjectName,
	)
	return i, err
}
