// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: issues.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProjectIssues = `-- name: CountProjectIssues :one
SELECT COUNT(*)
FROM issues
WHERE
  project_id = $1
  AND (
    $2::text = ''
    OR title ILIKE '%' || $2::text || '%'
    OR description ILIKE '%' || $2::text || '%'
  )
  AND (
    $3::text = ''
    OR status = $3::text
  )
  AND (
    $4::text = ''
    OR priority = $4::text
  )
`

type CountProjectIssuesParams struct {
	ProjectID int64
	Q         string
	Status    string
	Priority  string
}

func (q *Queries) CountProjectIssues(ctx context.Context, arg CountProjectIssuesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectIssues,
		arg.ProjectID,
		arg.Q,
		arg.Status,
		arg.Priority,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIssue = `-- name: CreateIssue :one
WITH inserted AS (
    INSERT INTO issues (
      project_id,
      title,
      description,
      status,
      priority,
      due_date
    )
    SELECT
      $1,
      $2,
      $3,
      $4,
      $5,
      $6
    WHERE EXISTS (
      SELECT 1
      FROM projects
      WHERE id = $1
    )
    RETURNING
      id,
      project_id,
      title,
      description,
      status,
      priority,
      due_date,
      created_at,
      updated_at
)
SELECT
  i.id,
  i.title,
  i.description,
  i.status,
  i.priority,
  i.due_date,
  i.created_at,
  i.updated_at,
  p.id          AS project_id,
  p.name        AS project_name
FROM inserted i
JOIN projects p ON p.id = i.project_id
`

type CreateIssueParams struct {
	ProjectID   int64
	Title       string
	Description string
	Status      string
	Priority    string
	DueDate     pgtype.Date
}

type CreateIssueRow struct {
	ID          int64
	Title       string
	Description string
	Status      string
	Priority    string
	DueDate     pgtype.Date
	CreatedAt   time.Time
	UpdatedAt   time.Time
	ProjectID   int64
	ProjectName string
}

func (q *Queries) CreateIssue(ctx context.Context, arg CreateIssueParams) (CreateIssueRow, error) {
	row := q.db.QueryRow(ctx, createIssue,
		arg.ProjectID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.DueDate,
	)
	var i CreateIssueRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProjectID,
		&i.ProjectName,
	)
	return i, err
}

const getIssue = `-- name: GetIssue :one
SELECT
  i.id,
  i.title,
  i.description,
  i.status,
  i.priority,
  i.created_at,
  i.updated_at,
  i.due_date,
  p.id AS project_id,
  p.name AS project_name
FROM issues i
JOIN projects p ON p.id = i.project_id
WHERE i.id = $1
`

type GetIssueRow struct {
	ID          int64
	Title       string
	Description string
	Status      string
	Priority    string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DueDate     pgtype.Date
	ProjectID   int64
	ProjectName string
}

func (q *Queries) GetIssue(ctx context.Context, issueID int64) (GetIssueRow, error) {
	row := q.db.QueryRow(ctx, getIssue, issueID)
	var i GetIssueRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DueDate,
		&i.ProjectID,
		&i.ProjectName,
	)
	return i, err
}

const getProjectIssuesList = `-- name: GetProjectIssuesList :many
SELECT
  id,
  title,
  status,
  priority
FROM issues
WHERE
  project_id = $1
  AND (
    $2::text = ''
    OR title ILIKE '%' || $2::text || '%'
    OR description ILIKE '%' || $2::text || '%'
  )
  AND (
    $3::text = ''
    OR status = $3::text
  )
  AND (
    $4::text = ''
    OR priority = $4::text
  )
ORDER BY created_at DESC, id DESC
LIMIT $6
OFFSET $5::bigint
`

type GetProjectIssuesListParams struct {
	ProjectID  int64
	Q          string
	Status     string
	Priority   string
	Skip       int64
	LimitCount int32
}

type GetProjectIssuesListRow struct {
	ID       int64
	Title    string
	Status   string
	Priority string
}

func (q *Queries) GetProjectIssuesList(ctx context.Context, arg GetProjectIssuesListParams) ([]GetProjectIssuesListRow, error) {
	rows, err := q.db.Query(ctx, getProjectIssuesList,
		arg.ProjectID,
		arg.Q,
		arg.Status,
		arg.Priority,
		arg.Skip,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProjectIssuesListRow{}
	for rows.Next() {
		var i GetProjectIssuesListRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.Priority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
