// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Comment struct {
	ID        int64
	IssueID   int64
	Text      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Issue struct {
	ID          int64
	ProjectID   int64
	Title       string
	Description string
	Status      string
	Priority    string
	DueDate     pgtype.Date
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Project struct {
	ID          int64
	Name        string
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
