// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"
	"time"
)

const countProjects = `-- name: CountProjects :one
SELECT COUNT(*)
FROM projects
WHERE (
  name ILIKE '%' || $1::text || '%'
  OR description ILIKE '%' || $1::text || '%'
)
`

func (q *Queries) CountProjects(ctx context.Context, q_ string) (int64, error) {
	row := q.db.QueryRow(ctx, countProjects, q_)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO
  projects (
    name,
    description,
    created_at,
    updated_at
  )
VALUES
  ($1, $2, $3, $4) RETURNING id,
  name,
  description,
  created_at,
  updated_at
`

type CreateProjectParams struct {
	Name        string
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.Name,
		arg.Description,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :one
DELETE FROM projects
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteProject(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, deleteProject, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const getProject = `-- name: GetProject :one
SELECT
  id,
  name,
  description,
  created_at,
  updated_at
FROM projects
WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id int64) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectsList = `-- name: GetProjectsList :many
SELECT
  id,
  name,
  description
FROM projects
WHERE (
  name ILIKE '%' || $1::text || '%'
  OR description ILIKE '%' || $1::text || '%'
)
ORDER BY created_at DESC, id DESC
LIMIT $3
OFFSET $2::bigint
`

type GetProjectsListParams struct {
	Q          string
	Skip       int64
	LimitCount int32
}

type GetProjectsListRow struct {
	ID          int64
	Name        string
	Description string
}

func (q *Queries) GetProjectsList(ctx context.Context, arg GetProjectsListParams) ([]GetProjectsListRow, error) {
	rows, err := q.db.Query(ctx, getProjectsList, arg.Q, arg.Skip, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProjectsListRow{}
	for rows.Next() {
		var i GetProjectsListRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
