// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CountProjects(ctx context.Context, q_ string) (int64, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	DeleteProject(ctx context.Context, id int64) (int64, error)
	GetProject(ctx context.Context, id int64) (Project, error)
	GetProjectsList(ctx context.Context, arg GetProjectsListParams) ([]GetProjectsListRow, error)
}

var _ Querier = (*Queries)(nil)
