// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	CountIssueComments(ctx context.Context, arg CountIssueCommentsParams) (int64, error)
	CountProjectIssues(ctx context.Context, arg CountProjectIssuesParams) (int64, error)
	CountProjects(ctx context.Context, q_ string) (int64, error)
	CreateComment(ctx context.Context, arg CreateCommentParams) (CreateCommentRow, error)
	CreateIssue(ctx context.Context, arg CreateIssueParams) (CreateIssueRow, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	DeleteIssue(ctx context.Context, issueID int64) (int64, error)
	DeleteProject(ctx context.Context, projectID int64) (int64, error)
	GetComment(ctx context.Context, commentID int64) (GetCommentRow, error)
	GetIssue(ctx context.Context, issueID int64) (GetIssueRow, error)
	GetIssueCommentsList(ctx context.Context, arg GetIssueCommentsListParams) ([]GetIssueCommentsListRow, error)
	GetProject(ctx context.Context, id int64) (Project, error)
	GetProjectIssuesList(ctx context.Context, arg GetProjectIssuesListParams) ([]GetProjectIssuesListRow, error)
	GetProjectsList(ctx context.Context, arg GetProjectsListParams) ([]GetProjectsListRow, error)
	UpdateIssue(ctx context.Context, arg UpdateIssueParams) (UpdateIssueRow, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
}

var _ Querier = (*Queries)(nil)
